name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Run fastai nbdev workflow
      uses: fastai/workflows/nbdev-ci@master
